### PR TITLE
Milestone 2: Friendship

### PR DESCRIPTION
**Pull request by NtwaliHeritier**
In this milestone, we implemented the friendship association in the social media app, where a user can follow another user.

### CODE REVIEW

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Lamia Sristy & Heritier Ntwali** 
Good job with the tests :muscle:  :muscle:
Your project meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [ ] Fix rubocop offenses
- [ ] In app/models/user.rb, remove duplicated code
- [ ] User can invite friends (screenshot from Pathwright)
- [ ] User can see friendships requests (screenshot from Pathwright)
- [ ] User has to accept friendship request to start friendship (screenshot from Pathwright)
- [ ] User can reject a friendship request (screenshot from Pathwright)
- [ ] There is a button to invite user to friendship on users list page and on single user page (screenshot from Pathwright)
- [ ] Posts timeline includes posts written by logged-in user and their friends
- [ ] Add a screenshot to the README file

Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team
### You have done well so far :clap: However, you have a few issues to fix:-
- [ ] Fix the linting errors and rubocop in the project - [Follow this guide](https://github.com/microverseinc/linters-config/tree/master/ror#troubleshooting)
- [ ] Remove stickler file as we no longer use it, rather use github actions as recommended by Microverse
### Make the changes and submit for another code review. Good luck.
- Happy coding!

**Review by Dandush03 — CHANGES_REQUESTED** [review]
# Status: :red_circle: Require Changes :red_circle: 
### Great Work! I know this can be frustrated but you must activate your GH Action so it will review your PR and fix any issue that may come along with it. Here ill leave a [link](https://github.com/microverseinc/linters-config/tree/master/ror) to help you set it up

# Happy Coding :nerd_face: :computer:

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
## Status: Request changes :recycle:
#### Hi @NtwaliHeritier and @LamiaSristy :clap: :clap:
#### Good job so far :+1: However, the linter is not enabled as pointed out by the last reviewer. Please, enable the linter and submit for another review.

#### _Reviewed by Temitayo Adeleke_

**Review by tirthajyoti-ghosh — APPROVED** [review]
# Approved ✅

## You have done an incredible job making this project 👏🧨💪! Just perfect 💯! 

### You have met all the requirements of the project. Go ahead and merge it! Onto the next project 🚀 !

Happy coding 👨‍💻 

<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

**Pull request merged**
